baseURL = "/"
languageCode = "en-ca"
title = "Vek Labs"
ISO8601 = "2006-01-02T15:04:05JST"

[params]
bannerShow = 7500 # Time that the banner is shown for in milliseconds
disallow_search_engines = false # set robots.txt to disallow everything
imgSizes = [2500, 1500, 1000, 500]
title = "Vek Labs"
videos = ["https://player.vimeo.com/external/407838186.hd.mp4?s=ddf843d553ee2d63b3c4c357ad3f59988342b03d&profile_id=175"]
locale = "en_CA"
images = ["/images/tempHero.jpg"]
subtitle = "Top Calgary Video Production Company"
description = "We're a Calgary video production company working with people on productions that inspire us. Meet Calgary's pro content team."

enableRobotsTXT = true
disableAliases = true
Paginate = 5

googleAnalytics = "GTM-MNN7HSW"

staticDir = ["static"]

invisibleSections = ["team", "videos", "category", "type"]

# Global CTA
[params.cta]
title = "Get In Touch"
description = "Our team is here for you!"
button_title = "Email"
button_link = "info@veklabs.com"

[menu]
[[menu.main]]
 identifier = "features"
 name = "Features"
 url = "/features/"
 weight = 1

 [[menu.main]]
 identifier = "services"
 name = "Services"
 url = "/services/"
 weight = 2
 
 [[menu.main]]
 identifier = "reports"
 name = "Reports"
 url = "/reports/"
 weight = 4

 [[menu.main]]
 identifier = "testimonials"
 name = "Testimonials"
 url = "/testimonials/"
 weight = 5


[taxonomies]
 category = "category"
 type = "type"

[related]
threshold = 50.0
includeNewer = true
toLower = true

[[related.indices]]
 name = "category"
 weight = 100.0

[[related.indices]]
 name = "author"
 weight = 50.0

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true