# local_backend: true

backend:
 name: git-gateway
 branch: master
logo_url: /assets/logo-black.svg
locale: en
media_folder: assets/images
public_folder: images
collections:
 - name: "reports"
   label: "Reports"
   folder: "content/reports"
   label_singular: "Report"
   create: true
   slug: "{{slug}}"
   delete: true
   fields:
    - { name: "image", label: "image", widget: "image" }
    - { name: "category", label: "category", widget: "string" }
    - { name: "date", label: "date", widget: "datetime" }
    - { name: "title", label: "title", widget: "string" }
    - name: "author"
      label: "author"
      widget: "relation"
      collection: "team"
      search_fields: ["name"]
      value_field: "name"
      display_fields: ["name"]
    - { name: "keywords", label: "keywords", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }
 - name: pages
   label: Pages
   files:
    - label: Home
      name: home
      file: content/_index.md
      editor: { preview: false }
      fields:
       - { name: title, label: Title, widget: string }
       - name: featured
         label: Featured
         widget: list
         fields:
          - { name: brand, label: Brand Name, widget: string }
          - { name: logo, label: Logo Image, widget: image }
       - name: offerings
         label: Offerings
         widget: list
         fields:
          - { name: title, label: Title, widget: string }
          - { name: image, label: Image, widget: image }
          - {
             name: tag,
             label: Heading Level,
             widget: select,
             options: ["h1", "h2", "h3"],
            }
          - { name: description, label: Description, widget: text }
 - name: "team"
   label: "Team"
   folder: "content/team"
   create: true
   identifier_field: name
   slug: "{{name}}"
   label_singular: "Team Member"
   editor: { preview: true }
   fields:
    - { name: "name", label: "name", widget: "string" }
    - { name: "image", label: "image", widget: "image" }
    - {
       name: "competencies",
       label: "competencies",
       widget: "list",
       default: [],
      }
    - { name: "title", label: "title", widget: "string" }
    - { name: "order", label: "order", widget: "number" }
    - { name: "body", label: "Body", widget: "markdown" }

 - name: "videos"
   label: "Videos"
   folder: "content/videos"
   create: true
   slug: "{{title}}"
   label_singular: "Video"
   editor: { preview: true }
   fields:
    - { name: "title", label: "title", widget: "string" }
    - { name: "videoID", label: "videoID", widget: "string" }
    - { name: "videoURL", label: "videoURL", widget: "string" }
    - { name: "previewURL", label: "previewURL", widget: "string" }
    - { name: "image", label: "image", widget: "image" }
    - {
       name: "type",
       label: "type",
       widget: "select",
       options:
        [
         "Entertainment",
         "Promotional",
         "Social Media",
         "Corporate",
         "Short Documentary",
        ],
      }

 - name: "features"
   label: "Features"
   folder: "content/features"
   create: true
   slug: "{{title}}"
   label_singular: "Feature"
   editor: { preview: false }
   fields:
    - { name: "title", label: "title", widget: "string" }
    - { name: "category", label: "category", widget: "string" }
    - { name: "videoURL", label: "videoURL", widget: "string" }
    - { name: "videoID", label: "videoID", widget: "string" }
    - {
       name: "publishDate",
       label: "publishDate",
       widget: "datetime",
       date_format: "YYYY-MM-DD",
      }
    - { name: "image", label: "image", widget: "image" }
    - {
       name: "site",
       label: "site",
       widget: "string",
       pattern: ["https://.*", "Must be a valid URL"],
      }
    - { name: "body", label: "Body", widget: "markdown" }

 - name: "services"
   label: "Services"
   folder: "content/services"
   create: true
   slug: "{{title}}"
   label_singular: "Service"
   identifier_field: title
   editor: { preview: false }
   fields:
    - { name: "title", label: "title", widget: "string" }
    - { name: "page_title", label: "page_title", widget: "string" }
    - { name: "image", label: "image", widget: "image" }
    - { name: "order", label: "order", widget: "number" }
    - { name: "speed", label: "speed", widget: "number" }
    - { name: "summary", label: "summary", widget: "text" }
    - { name: "body", label: "Body", widget: "markdown" }

 - name: "settings"
   label: "Settings"
   files:
    - label: "Site Settings"
      name: "config"
      file: config.toml
      editor: { preview: false }
      create: false
      delete: false
      format: toml
      fields:
       - { required: true, "Site Title", name: "title", widget: "string" }
       - { label: Site URL, name: baseURL, widget: string }
       - title: "Parameters"
         name: "params"
         widget: "object"
         fields:
          - { label: Site Description, name: description, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - {
             label: Items per page,
             name: Paginate,
             widget: number,
             hint: Number of items to show per page,
            }
          - label: Call to Action
            name: cta
            hint: This is the call to action that appears across the site
            widget: object
            summary: "{{fields.title}} - {{fields.description}}"
            fields:
             - { label: Title, name: title, widget: string }
             - { label: Description, name: description, widget: string }
             - { label: Button Text, name: button_title, widget: string }
             - { label: Button URL, name: button_link, widget: string }
          - {
             label: Google Analytics ID,
             name: googleAnalytics,
             widget: string,
            }
          - {
             label: Banner Shown Time,
             name: bannerShow,
             widget: number,
             hint: Time that the banner is shown for in milliseconds,
            }
          - {
             label: Open Graph Images,
             name: images,
             widget: "list",
             label_singular: "Image",
             fields: [{ label: Image, name: image, widget: "image" }],
            }
          - {
             label: Open Graph Videos,
             name: videos,
             widget: "list",
             label_singular: "Video",
             fields: [{ label: URL, name: url, widget: "string" }],
            }
    - name: content-settings
      label: Content Settings
      file: data/en.toml
      editor: { preview: false }
      create: false
      delete: false
      format: toml
      fields:
       - {
          name: EMAIL,
          label: Email,
          widget: string,
          pattern: ["[^@]+@[^@]+", "Must be an email"],
         }
       - {
          name: PHONE,
          label: Phone,
          widget: string,
          pattern:
           [
            "[0-9]{3}-[0-9]{3}-[0-9]{4}",
            "Phone number must be in the format 123-456-7890",
           ],
         }
       - { name: subtitle, label: Subtitle, widget: string }
       - { name: description, label: Description, widget: string }
       - { name: HERO_EXCERPT, label: Hero Excerpt, widget: string }
       - { name: TEAM_TITLE, label: Team Title, widget: string }
       - { name: PROJECTS_FILMED, label: Projects Filmed, widget: number }
       - { name: VIDEOS_RENDERED, label: Videos Rendered, widget: number }
       - {
          name: FOOTAGE_PROCESSED_TB,
          label: Footage Processed Tb,
          widget: number,
         }
       - { name: TOTAL_VIEWS, label: Total Views, widget: number }
       - { name: CLIENT_TITLE, label: Client Title, widget: string }
       - { name: CLIENT_SUB_TITLE, label: Client Sub Title, widget: string }
       - { name: FOOTER_PRETEXT, label: Footer Pretext, widget: string }
    - name: footer-settings
      label: Footer Settings
      file: data/footer.toml
      editor: { preview: false }
      create: false
      delete: false
      format: toml
      fields:
       - { name: mail, label: Mailing Address, widget: string }
       - name: social
         label: Social Media
         widget: object
         fields:
          - name: channel
            label: Channels
            widget: list
            summary: "{{fields.name}} - {{fields.url}}"
            fields:
             - { name: name, label: Name, widget: string }
             - {
                name: url,
                label: URL,
                widget: string,
                pattern: ["https://.*", "Must be a valid URL"],
               }
             - { name: icon, label: Icon, widget: image }
